site_name: 下落式音游齐民要术
site_url: https://electrowind.github.io/VSRG-4K-wiki

theme:
  language: 'zh'
  name: material
  palette:
    scheme: nthing
    primary: white
    accent: green

  features:
    - search.highlight
    - navigation.instant
    - navigation.tabs
    # - navigation.footer
    - content.action.edit
    - content.action.view

repo_url: https://github.com/electrowind/VSRG-4K-wiki
repo_name: electrowind/VSRG-4K-wiki

plugins:
  - search

  # - git-committers:
  #     repository: electrowind/VSRG-4K-wiki
  #     branch: main

markdown_extensions:
   - pymdownx.arithmatex:
       generic: true
   - pymdownx.betterem

extra_css:
  - stylesheets/extra.css

nav:
  - Home:
    - 前言: index.md
  - 基本常识: common.md
  - 键型:
    - Index: pattern/index.md
    - 排列: pattern/pailie.md
    - 常规: pattern/rice.md